services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: app-back
        container_name: app-back
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - mysql
        volumes:
            - ./:/var/www
        # ports:
        #     - 8080:80
        networks:
            - app-dev
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - app-dev
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    nginx:
        image: nginx:stable-alpine
        container_name: nginx-dev
        restart: unless-stopped
        depends_on:
            - app
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - app-dev

networks:
    app-dev:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
